# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=dev.hybridlabs.hapi
java_version=17
kotlin_version=2.1.20

# Common
minecraft_version=1.20.1
mod_name=Hybrid API
mod_author=Hybrid Labs
mod_id=hapi
license=MIT

credits=MysticKoko, Aqua, Andante, Eggo, murphy slaw, Ragno

description=A library mod used by the Hybrid Labs suite

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_version=2023.09.03

# Dependencies
geckolib_version=1.20.1:4.8.2

# Fabric
loom_version=1.10-SNAPSHOT
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.18.2

# Forge
forge_version=47.4.10
minecraft_version_range=[1.20.1, 1.22)
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false